// Generated by CoffeeScript 1.3.3
(function() {

  jQuery(document).ready(function($) {
    var Page, Person, PersonImage, page;
    PersonImage = (function() {

      function PersonImage(element, imageSize) {
        this.element = element;
        this.imageSize = imageSize;
        $(this.element).attr('width', this.imageSize);
        $(this.element).attr('height', this.imageSize);
        $(this.element).attr('person-name', $(this.element).attr('title'));
        $(this.element).removeAttr('title');
      }

      PersonImage.prototype.doLowOpacity = function() {
        return $(this.element).css({
          'opacity': '.8'
        });
      };

      PersonImage.prototype.doFullOpacity = function() {
        return $(this.element).css({
          'opacity': '1'
        });
      };

      return PersonImage;

    })();
    Person = (function() {

      function Person(name, title, description, index, image) {
        this.name = name;
        this.title = title;
        this.description = description;
        this.index = index;
        this.image = image;
      }

      return Person;

    })();
    Page = (function() {

      function Page(imageSize) {
        var _this = this;
        this.imageSize = imageSize;
        this.captionElements = $('.entry_content .wp-caption');
        this.tooltipBackgroundImage = new Image();
        this.tooltipBackgroundImage.src = "/wp-includes/images/people-tooltip.png";
        this.tooltipArrowImage = new Image();
        this.tooltipArrowImage.src = "/wp-includes/images/people-arrow.png";
        this.people = $([]);
        this.captionElements.each(function(i, e) {
          var image;
          image = $(e).find('img').first();
          return _this.people.push(new Person($(image).attr('title'), $(image).attr('alt'), $(e).find('.wp-caption-text').first().text(), i + 1, new PersonImage(image, _this.imageSize)));
        });
      }

      Page.prototype.setupPage = function() {
        var _this = this;
        this.captionElements.each(function(i, e) {
          $(e).removeClass();
          $(e).css({
            'width': _this.imageSize,
            'height': _this.imageSize,
            'float': 'left'
          });
          return $(e).find('p').first().hide();
        });
        return this.people.each(function(i, e) {
          $(e.image.element).after("<div class='tooltip' style='display:none'>\n    <p class='name'>" + e.name + "</p>\n\n    <p class='title'>" + e.title + "</p>\n\n    <p class='description'>" + e.description + "</p>\n</div>");
          return $(e.image.element).tooltip({
            'tooltipcontentclass': 'tooltip-content',
            'position': 'bottom center',
            'offset': [-5, 76]
          });
        });
      };

      return Page;

    })();
    page = new Page('140');
    return page.setupPage();
  });

}).call(this);
